### ISSUE TITLE
大佬考虑添加bark推送支持吗

### ISSUE THREAD

**Issue by 2beetle** [Ccccx159/Emby_Notifier#31]
大佬考虑添加[bark](https://bark.day.app/)推送支持吗

**Comment by Ccccx159** [comment]
预览版本已更新推送，2周后若无问题反馈，更新正式版本

~~~bash
docker pull b1gfac3c4t/emby_notifier_tg:Pre-release
~~~

![Image](https://github.com/user-attachments/assets/de8dc115-37dc-4fe3-988b-b0500229c79e)

**Comment by 2beetle** [comment]
> 预览版本已更新推送，2周后若无问题反馈，更新正式版本
> 
> docker pull b1gfac3c4t/emby_notifier_tg:Pre-release

我试了一下能否只使用bark好像不太行，是bug还是硬性要求必须有其他通知方式
`[2025-02-05 09:53:49] [main.py|env_check|83] [ERROR] : You must set up at least one notification method, such as a Telegram bot or a WeChat Work application.`

我的docker-compose文件
```yaml
version: '3'
services:
  emby_notifier_tg:
    build:
      context: .
      dockerfile: dockerfile
        #image: b1gfac3c4t/emby_notifier_tg:latest
    image: b1gfac3c4t/emby_notifier_tg:Pre-release
    environment:
      - TZ=Asia/Shanghai
      # 这里所有的环境变量都不要使用引号
      # 必填参数
      - TMDB_API_TOKEN=xxx
      - BARK_SERVER=xxx
      - BARK_DEVICE_KEYS="xxx"
```
